### ISSUE TITLE
File concatenation not idempotent (i.e. different results after multiple times with same input)

### ISSUE THREAD

**Issue by MPV** [ericclemmons/grunt-react#36]
Hi, 
We're a development team using grunt-react (which is awesome!) for compiling JSX to JS. We've recently enabled the file concatenation/combination feature and it works good, but we've got some problems that it seems to combine the files differently for different developers? We're all using version ~0.9.0, and for technical reasons we're still bound to checking in both our JSX and JS files into version control. 

After someone has made a change in the JSX file, compiled it into JS, committed and pushed — then someone else pulls down the code, grunt watch detects and recompiles the JS files again — now with different output. Why?

Here's an example from what "git diff" says has changed:
```
@@ -1134,7 +1134,7 @@ define('components/header__menu', ['react', 'utils', 'components/header__languag
     });
 
     return MobileMenu;
-});
+});
 /**
  * @jsx React.DOM
  */
```

As you might've guessed, that place is the end+beginning of 2 different files that are concatenated.

**Comment by ericclemmons** [comment]
Upon re-reading this, this appears to be a platform issue.  Otherwise, a test would be greatly appreciated, since I have no way of confirming the behavior on my end =/
