### ISSUE TITLE
bundle.js is no longer generated in grunt-react 0.12

### ISSUE THREAD

**Issue by sahat** [ericclemmons/grunt-react#46]
This code no longer works in `grunt-react@0.12`:

```js
browserify: {
  options: {
    transform: [require('grunt-react').browserify]
  },
 client: {
    src: 'react/main.js',
    dest: 'static/js/bundle.js'
  }
}
```

It works fine in 0.10 and 0.11. Perhaps a bug in https://github.com/ericclemmons/grunt-react/commit/0128961d05be92ba789dcc9dc4a2c9e1731469d3?

Update: Tested with the latest version of browserify.

**Comment by ericclemmons** [comment]
Interesting!  The tests broke when I updated dependencies (4616831af75f6a2c13e67965ae29fc8906f0c789), then I had to rewrite the transform (0128961d05be92ba789dcc9dc4a2c9e1731469d3) for them to pass again.

> https://github.com/ericclemmons/grunt-react/blob/73b41bf82b6b6f33a5cf7eb6bd9ad3dfc63c19a1/Gruntfile.js#L26-L35

What version of Browserify are you using?

**Comment by sahat** [comment]
Hey @ericclemmons, I am using `grunt-browserify` 3.5.0, which uses `browserify` ^9.0.3.

**Comment by AurelioDeRosa** [comment]
I have the issue but a part of my problem was solved replacing `option` with `browserifyOptions`. However, the process doesn't recognize jsx files anymore (it gives an error as soon as it reaches a tag).

**Comment by adambbecker** [comment]
:+1: 

Gave @apendua's cc2acf0 a try and confirm that its does allow the `browserify` task to run as intended.

**Comment by ericclemmons** [comment]
`v0.12.1` is out with this fix, thanks to @apendua!

**Comment by apendua** [comment]
@ericclemmons Nice!
