### ISSUE TITLE
app.built.js

### ISSUE THREAD

**Issue by tielur** [ericclemmons/grunt-react#50]
This is more of a question then an issue. I'm new to both Hapi and React but I'm curious why the `app.built.js` is so large. It looks like grunt is calling browserify on the src/react_components/ directory but the `app.built.js` has a lot of other stuff in it. Is this common? Is all of the extra stuff just React?

**Comment by ericclemmons** [comment]
Yes, so there are a couple things.  There's the entire tree (including React), and the fact that the _dev_ version of React is being bundled.  Also, IIRC, I _think_ debug mode may be on (are you seeing sourcemaps?)

Some googling did return this:

> If you want to use Browserify you can substantially reduce build size by setting the NODE_ENV=production environment variable when running Browserify (it strips out error messages and other things).

> https://groups.google.com/forum/#!topic/reactjs/UnZRsJgSzHE

Best of luck, and if you have any major epiphanies I'd <3 to hear 'em!
