### ISSUE TITLE
Publish new version to npm

### ISSUE THREAD

**Issue by tofumatt** [ericclemmons/grunt-react#56]
The README explains the project is deprecated, but the module page on npm doesn't have this info as it wasn't pushed.

Could you push a new version to npm so users there know to use `grunt-babel`? Thanks!

**Comment by ericclemmons** [comment]
@tofumatt Good call!  Should be fixed now via `v0.12.3`:

> https://www.npmjs.com/package/grunt-react

**Comment by tofumatt** [comment]
Thanks very much! 😀
- Matthew Riley MacPherson | tofumatt.com
