### ISSUE TITLE
grunt-react not work on react 0.13.3

### ISSUE THREAD

**Issue by idamag** [ericclemmons/grunt-react#57]
It will show error:  "Invariant Violation: React.render(): Invalid component element. This may be caused by unintentionally loading two independent copies of React."

**Comment by ericclemmons** [comment]
This is likely caused by known issues with React, React Addons, & Browserify internally.

Besides, this project has been deprecated in favor of Babel:

> https://github.com/ericclemmons/grunt-react#deprecation-notice

**Comment by idamag** [comment]
Thanks!
Because i wrote wrong code , it caused the issue.
